"""Build curated research hub, glossary and single-cell methods guide.
Content is hand-authored below, not fetched/generated by an AI service.
"""
import html
import json
from pathlib import Path
from seo_audit import ROOT, SITE

PHENO = 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7467707/'
BIOMASS = 'https://pmc.ncbi.nlm.nih.gov/articles/PMC9368473/'
MOTILITY = 'https://elifesciences.org/articles/76519'

HUB = '''
<p class="dek">Orr Biologicals explores two different questions: how to monitor a growing algae culture, and how to measure differences between individual microalgal cells. This directory connects the existing guides to the proposed Algaephyte and Cyanoflow architectures.</p>
<h2>Choose the question, not just the platform</h2>
<table><thead><tr><th>Research question</th><th>Starting point</th><th>Evidence needed</th></tr></thead><tbody>
<tr><td>How do light, carbon and nutrients affect a culture?</td><td><a href="/#inside">Algaephyte cultivation concept</a></td><td>Calibrated sensors, replicated cultures and model validation.</td></tr>
<tr><td>What variation does a population average hide?</td><td><a href="/cyanoflow">Cyanoflow single-cell concept</a></td><td>Reliable cell identity, controlled imaging and independently checked phenotypes.</td></tr>
<tr><td>Which organism fits a cultivation or live-feed question?</td><td><a href="/applications/#species">Microalgae and cyanobacteria species guides</a></td><td>Strain identity, relevant literature and application-specific validation.</td></tr>
</tbody></table>
<h2>Algae cultivation: a connected reading path</h2>
<p>Start with <a href="/blog/spirulina-is-a-cyanobacterium">why Spirulina is a cyanobacterium</a>, then <a href="/blog/how-to-start-home-spirulina-culture">the requirements of a starter culture</a>. Continue to <a href="/blog/zarrouk-medium-and-nutrients">Zarrouk medium and nutrients</a>, <a href="/blog/light-temperature-mixing">light, temperature and mixing</a>, and <a href="/blog/alkalinity-as-a-control-variable">alkalinity versus pH</a>. A visibly green culture is not proof of identity or food safety.</p>
<p>For other organisms, use <a href="/applications/how-to-grow-a-microalgae-culture">the microalgae cultivation guide</a> and the relevant species page. Conditions should not be copied blindly between strains.</p>
<h2>Sensors, growth models and bounded control</h2>
<p><a href="/blog/six-culture-signals-main-senses">The six proposed sensor channels</a> measure different aspects of a culture, not a single universal health score. Read <a href="/blog/dissolved-oxygen-stress-signal">dissolved-oxygen interpretation</a> and <a href="/blog/digital-twins-biological-cultivation">what a biological digital twin means</a> before <a href="/blog/digital-twin-droop-steele-model">Droop, Steele and light attenuation</a>.</p>
<p>The proposed controller is explained in <a href="/blog/control-loop-architecture">control-loop architecture</a>, <a href="/blog/bounded-autonomy-safe-ai-proposals">bounded AI proposals</a> and <a href="/blog/how-main-keeps-culture-safe">Algaephyte safety design requirements</a>. Model agreement is not independent proof that a dose is safe.</p>
<h2>Cyanoflow: single-cell observation before candidate claims</h2>
<p><a href="/blog/single-cell-microalgae-microfluidics">Single-cell microalgae methods</a> connects compartments, microscopy, tracking and validation. The <a href="/cyanoflow#pipeline">Cyanoflow pipeline</a> is a proposed workflow, not a published experiment. <a href="/blog/vision-contamination-detection">Computer-vision limitations</a> and <a href="/blog/edge-ai-biological-systems">edge-AI design tradeoffs</a> also apply to cultivation imaging, but neither establishes an experimentally validated phenotype.</p>
<h2>Methodology: what different evidence labels mean</h2>
<ul><li><strong>Literature-backed fact:</strong> attributed to a cited source; species, method and conditions matter.</li><li><strong>Research concept:</strong> a proposed mechanism or architecture still needing a test.</li><li><strong>Educational simulation:</strong> outputs from chosen equations or synthetic labels, not measurements of living cells.</li><li><strong>Prototype:</strong> a built component with documented conditions and limited test scope. A design drawing alone is not a tested prototype.</li><li><strong>Validated result:</strong> measurements with methods, controls, repeatability and stated limitations. No validated Orr hardware performance is presented here.</li></ul>
<p>When testing becomes possible, record strain identity, conditions, sensor calibration, sampling method, model version, exclusions and failed runs. Compare predictions to held-out observations; do not fit and evaluate on the same observations. Keep biological replicates distinct from repeated images of one cell.</p>
<h2>Authorship, sources and corrections</h2>
<p>The guides use the existing Orr Biologicals organizational byline. The homepage explains the project's educational origins; this site does not claim accredited laboratory status or invent degrees, publications or affiliations. Daily literature briefs are explicitly AI-assisted summaries of abstracts and can be wrong. Read the original paper before relying on a claim.</p>
<p>Older notes are being reviewed: a source list provides a route to verification, not certification of every historical numerical or food-safety statement. Consult <a href="/disclaimer">the scientific and safety disclaimer</a>. Send a source-linked correction to <a href="mailto:service@orrbiologicals.com">service@orrbiologicals.com</a>.</p>
<h2>Primary reading and next steps</h2>
<ul><li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC7467707/">Behrendt et al. (2020): PhenoChip single-cell photophysiology</a> — a separate research group's experimental work, not Cyanoflow validation.</li><li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC9368473/">Schagerl et al. (2022): reliable microalgal biomass and vitality measurements</a> — why optical proxies require care.</li></ul>
<p>Look up definitions in the <a href="/glossary">algae biotechnology glossary</a> or browse <a href="/blog/#kb">all cultivation and research notes</a>. The <a href="/#simulation">culture model</a> illustrates relationships; it cannot certify a real culture's safety.</p>
'''

GUIDE = '''
<p class="dek">Single-cell microalgae analysis measures individual cells rather than only the average of a culture. Microfluidic compartments can help keep cell identity and exposure conditions observable, while microscopy records how a cell changes. An image-derived candidate still needs independent biological validation.</p>
<h2>Why the culture average can miss useful variation</h2>
<p>Two cultures can share a similar average signal while containing different distributions of cell size, photosynthetic response or growth history. Single-cell measurements preserve that variation. The research question must specify the phenotype of interest and what observation would count as evidence, rather than ranking every visually unusual cell as useful.</p>
<p>In PhenoChip, Behrendt and colleagues studied individual photosynthetic cells under controlled chemical and thermal conditions using chlorophyll fluorometry. The reported work demonstrates a literature example of single-cell photophysiology, not an experiment performed by Orr Biologicals [1].</p>
<h2>Droplets, microwells and channels are different choices</h2>
<table><thead><tr><th>Compartment</th><th>Useful property</th><th>Question to validate</th></tr></thead><tbody>
<tr><td>Aqueous droplets in a carrier fluid</td><td>Separate small liquid volumes and potentially route selected compartments.</td><td>Does the interface affect viability, gas exchange, compounds or optical measurement?</td></tr>
<tr><td>Microwells within a flow channel</td><td>Keep cells in known positions while media or exposure conditions change.</td><td>Are the same cells retained and are their local conditions known?</td></tr>
<tr><td>Flow-through channels</td><td>Observe cells as they pass an imaging region.</td><td>Can a later image or recovered sample be tied to the same cell?</td></tr>
</tbody></table>
<p>PhenoChip uses microwell confinement and controlled gradients [1]. Its findings must not be used to imply that a proposed droplet-based Cyanoflow device has the same behavior. Confinement itself can change a measurement: Bentley and colleagues examine single-cell motility in microfluidic confinement [2].</p>
<h2>Single-cell loading is an observation, not a guarantee</h2>
<p>Dilution alone does not prove one cell per compartment. Under an ideal independent random-loading model, occupancy can be described by a Poisson distribution: empty, single and multiple-cell compartments all occur. Aggregation, filamentous organisms and unequal compartment sizes can invalidate that simple assumption. Verify occupancy from images and report rejected doublets or ambiguous compartments.</p>
<p>The <a href="/cyanoflow#pipeline">Cyanoflow pipeline</a> depicts dilute loading as a design concept. Its animation does not measure actual occupancy, droplet consistency or cell survival.</p>
<h2>Time-series microscopy: identity comes before growth estimates</h2>
<p>A sequence is useful only if frames belong to the same cell or lineage. Record acquisition intervals, magnification, pixel calibration, illumination, focus and compartment identity. Define how division, motion, occlusion and tracking loss are handled. Changing focus can change apparent area without biological growth; repeated illumination can alter the organism being observed.</p>
<p>Controls should separate imaging artifacts from biological change. Use repeated measurements to evaluate measurement repeatability, but do not count repeated frames of one cell as independent biological replicates. Time-dependent responses in the PhenoChip study illustrate why exposure history and observation method matter [1].</p>
<h2>Feature extraction is not biochemical confirmation</h2>
<p>Segmentation can turn images into area, aspect ratio, texture or intensity measurements. Those are operational measurements tied to a particular instrument and preprocessing method. Color or brightness alone is not proof of pigment concentration, species identity, viability or toxin absence. The biomass-monitoring roadmap explains why optical signals require appropriate calibration and interpretation [3].</p>
<p>A candidate rule should be declared before evaluating it. Keep validation runs, culture batches or lineages separate from training data so near-identical frames do not leak across the split. Report exclusions and ambiguous labels. Precision and recall describe a defined labeling task, not a universal measure of biological usefulness.</p>
<h2>Recovery and independent phenotype validation</h2>
<p>Finding an interesting image and recovering the corresponding living cell are distinct engineering problems. A recovery test needs to establish identity, viability, contamination control and successful downstream observation. Depending on the question, confirm the phenotype with an independent assay or regrowth under documented conditions. A simulation's label is not such an assay.</p>
<p>PhenoChip reports recovery and subsequent propagation in its own experimental system [1]. That is an informative reference for research design, not a promise of Cyanoflow recovery performance. The <a href="/cyanoflow#status">Cyanoflow status section</a> identifies its current conceptual scope.</p>
<h2>What Cyanoflow proposes, and what it has not demonstrated</h2>
<p>Cyanoflow proposes compartmentalization, time-series imaging, feature extraction, candidate ranking and eventually recovery. The current website provides illustrative imagery and synthetic interactive records. It does not establish device throughput, selection accuracy, biochemical productivity or inherited phenotypes.</p>
<p>Algaephyte is a different concept: monitoring and controlling culture-level conditions. Read the <a href="/research/">research methodology and topic map</a> for that distinction, or <a href="/blog/vision-contamination-detection">vision-based contamination detection limitations</a> for a related imaging question.</p>
<h2>References</h2>
<ol><li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC7467707/">Behrendt et al. (2020), PhenoChip: a single-cell phenomic platform for high-throughput photophysiological analyses of microalgae</a>. Science Advances. DOI: 10.1126/sciadv.abb2754. Primary experimental study.</li>
<li><a href="https://elifesciences.org/articles/76519">Bentley et al. (2022), Phenotyping single-cell motility in microfluidic confinement</a>. eLife. DOI: 10.7554/eLife.76519. Primary experimental study.</li>
<li><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC9368473/">Schagerl et al. (2022), Estimating biomass and vitality of microalgae for monitoring cultures</a>. Cells. DOI: 10.3390/cells11152455. Measurement methods and limitations.</li></ol>
<p>Definitions: <a href="/glossary#microfluidics">microfluidics</a>, <a href="/glossary#phenotyping">phenotyping</a> and <a href="/glossary#single-cell-analysis">single-cell analysis</a>. Next: <a href="/cyanoflow">explore the proposed Cyanoflow workflow</a>. No procedure here authorizes culturing unknown environmental organisms; follow relevant containment and institutional requirements.</p>
'''

TERMS = [
('cyanobacteria', 'Cyanobacteria', 'Photosynthetic bacteria. Unlike eukaryotic algae, they do not have a membrane-bound nucleus or chloroplast. Some are unicellular and others filamentous; neither appearance nor a broad taxonomic label establishes food safety.', '/blog/spirulina-is-a-cyanobacterium', 'Why Spirulina is a cyanobacterium'),
('microalgae', 'Microalgae', 'A practical grouping of microscopic photosynthetic organisms, not a single taxonomic lineage. Applied literature sometimes includes cyanobacteria alongside eukaryotic microalgae. State which organism and strain a claim concerns.', '/applications/', 'Organisms and applications'),
('arthrospira', 'Arthrospira and Spirulina', 'Spirulina is a common commercial name associated with filamentous cyanobacteria historically called Arthrospira. Scientific naming changes, so strain identity and the naming used by a source matter more than a market label alone.', '/applications/species/arthrospira', 'The Arthrospira species guide'),
('photobioreactor', 'Photobioreactor', 'A cultivation system that supplies light to photosynthetic organisms while managing culture conditions. Vessel geometry, light path, gas exchange, nutrients and temperature interact; enclosure alone does not guarantee sterility or productivity.', '/blog/what-is-main-plain-language', 'The proposed Algaephyte architecture'),
('optical-density', 'Optical density', 'A logarithmic measure of light attenuation through a sample relative to a reference. In cell suspensions it includes scattering as well as absorption. Record wavelength, path length, blank and dilution; converting it to biomass requires an appropriate calibration [2].', '/blog/six-culture-signals-main-senses', 'Interpreting the proposed sensor suite'),
('dissolved-oxygen', 'Dissolved oxygen', 'Oxygen present in solution, commonly reported as concentration or percent saturation. Temperature, salinity, calibration and gas exchange affect interpretation. A high value alone does not establish cell damage or a universal stress threshold.', '/blog/dissolved-oxygen-stress-signal', 'Dissolved oxygen in culture monitoring'),
('photoinhibition', 'Photoinhibition', 'A reduction in photosynthetic performance associated with excess light relative to an organism’s ability to use and dissipate absorbed energy. Response depends on strain, exposure history and conditions; brighter illumination is not always more useful.', '/blog/light-temperature-mixing', 'Light, temperature and mixing'),
('beer-lambert', 'Beer–Lambert attenuation', 'An idealized exponential relationship between light transmission, path length and attenuating material. Dense, scattering cultures and changing pigment composition can violate simple assumptions; treat a fitted attenuation coefficient as condition-dependent [2].', '/blog/digital-twin-droop-steele-model', 'Assumptions in the algae growth model'),
('droop-model', 'Droop model', 'A nutrient-quota growth model in which growth depends on nutrient stored within a cell rather than only on the dissolved nutrient outside it. Choosing a quota model does not establish fitted parameters or predictive accuracy for a particular culture.', '/blog/digital-twin-droop-steele-model', 'Droop and Steele in a proposed twin'),
('digital-twin', 'Digital twin', 'A model associated with a particular physical system and updated using observations of that system. An uncalibrated educational simulation is not a validated twin of a working reactor. Forecast usefulness must be evaluated against held-out measurements.', '/blog/digital-twins-biological-cultivation', 'Digital twins for living cultures'),
('microfluidics', 'Microfluidics', 'Handling fluids in small channels or compartments where geometry and interfaces strongly shape transport. Droplets, microwells and flow-through channels solve different observation problems; their effects on cells must be tested [1].', '/blog/single-cell-microalgae-microfluidics', 'Single-cell microalgae methods'),
('phenotyping', 'Phenotyping', 'Measuring observable characteristics under defined conditions. Image features may be useful proxies, but a label such as productive or stress-tolerant requires a declared biological measurement and appropriate validation [1].', '/cyanoflow', 'The Cyanoflow research concept'),
('single-cell-analysis', 'Single-cell analysis', 'Measurements resolved to an individual cell or lineage rather than only a pooled average. Maintaining identity across images, division events and recovery is essential; repeated frames are not independent biological samples [1].', '/blog/single-cell-microalgae-microfluidics', 'Tracking and validation limitations'),
('machine-vision', 'Machine vision', 'Computational extraction of information from images. Segmentation, tracking and classification depend on imaging conditions and labeled examples. Confidence scores do not certify organism identity, food safety or actuator safety.', '/blog/vision-contamination-detection', 'Vision limitations and validation'),
]


def glossary():
    body = '<p class="dek">Definitions for reading algae cultivation and single-cell research, with the measurement limitations that short dictionary entries often omit. Each term links to a deeper explanation.</p>\n<nav aria-label="Glossary terms"><p>'
    body += ' · '.join('<a href="#' + slug + '">' + html.escape(name) + '</a>' for slug, name, *_ in TERMS) + '</p></nav>'
    for slug, name, text, link, anchor in TERMS:
        body += '<section id="' + slug + '"><h2>' + html.escape(name) + '</h2><p>' + html.escape(text) + '</p><p><a href="' + link + '">' + html.escape(anchor) + '</a></p></section>\n'
    return body + '<h2>Sources and scope</h2><p>[1] <a href="' + PHENO + '">Behrendt et al. (2020), PhenoChip</a>. [2] <a href="' + BIOMASS + '">Schagerl et al. (2022), biomass and vitality measurement methods</a>. These sources explain measurement practice, not validated performance of Orr Biologicals hardware.</p><p>Use the <a href="/research/">research topic and methodology hub</a> to choose a reading path. This glossary is educational, not a cultivation protocol or food-safety assessment.</p>'


def build():
    template = (ROOT / 'blog/spirulina-is-a-cyanobacterium.html').read_text(encoding='utf-8')
    header = template[template.index('<header'):template.index('<div class="art-shell">')]
    for rel, title, description, body, article in [
        ('research/index.html', 'Algae Cultivation & Single-Cell Research Methods | Orr Biologicals', 'Explore Algaephyte cultivation models, Cyanoflow single-cell methods, species guides and transparent research-status labels. Concepts are not validated results.', HUB, False),
        ('glossary.html', 'Algae Biotechnology Glossary: Models, Sensors & Cells | Orr Biologicals', 'Understand microalgae, cyanobacteria, optical density, photobioreactors, digital twins, microfluidics and phenotyping, with limitations and deeper reading.', glossary(), False),
        ('blog/single-cell-microalgae-microfluidics.html', 'Single-Cell Microalgae Analysis with Microfluidics | Orr Biologicals', 'Compare droplets and microwells for microalgae analysis. Learn how imaging, tracking, phenotype validation and recovery differ, with primary research references.', GUIDE, True),
    ]:
        url = SITE + ('/research/' if rel == 'research/index.html' else '/' + rel[:-5])
        h1 = {'research/index.html': 'Algae cultivation and single-cell research methods',
              'glossary.html': 'Algae biotechnology glossary',
              'blog/single-cell-microalgae-microfluidics.html': 'Single-cell microalgae analysis with microfluidics'}[rel]
        graph = [{'@type': 'Article' if article else 'CollectionPage' if rel.startswith('research') else 'WebPage',
            '@id': url + '#page', 'url': url, 'name': title, 'description': description,
            'isPartOf': {'@id': SITE + '/#site'}}]
        if article: graph[0].update({'headline': h1, 'datePublished': '2026-10-04', 'dateModified': '2026-10-04',
            'author': {'@type': 'Organization', 'name': 'Orr Biologicals', 'url': SITE + '/research/'},
            'publisher': {'@type': 'Organization', 'name': 'Orr Biologicals', 'url': SITE + '/'}, 'mainEntityOfPage': url})
        graph.append({'@type': 'BreadcrumbList', 'itemListElement': [
            {'@type': 'ListItem', 'position': 1, 'name': 'Orr Biologicals', 'item': SITE + '/'},
            {'@type': 'ListItem', 'position': 2, 'name': h1, 'item': url}]})
        e = lambda s: html.escape(s, quote=True)
        page = '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        page += '<title>' + e(title) + '</title>\n<meta name="description" content="' + e(description) + '">\n<link rel="canonical" href="' + url + '">\n'
        page += '<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg">\n<meta property="og:type" content="' + ('article' if article else 'website') + '">\n'
        for key, value in [('og:title', title), ('og:description', description), ('og:url', url), ('og:image', SITE + '/assets/og.png'), ('og:site_name', 'Orr Biologicals')]:
            page += '<meta property="' + key + '" content="' + e(value) + '">\n'
        page += '<meta name="twitter:card" content="summary_large_image">\n<meta name="twitter:title" content="' + e(title) + '">\n<meta name="twitter:description" content="' + e(description) + '">\n<meta name="twitter:image" content="' + SITE + '/assets/og.png">\n'
        if article: page += '<meta property="article:published_time" content="2026-10-04">\n<meta property="article:modified_time" content="2026-10-04">\n'
        page += '<script type="application/ld+json">' + json.dumps({'@context': 'https://schema.org', '@graph': graph}, ensure_ascii=False) + '</script>\n'
        page += '<link rel="stylesheet" href="/css/extras.css">\n<link rel="stylesheet" href="/css/header.css?v=20260926a">\n</head>\n<body class="art-body">\n' + header
        page += '<main class="art-shell"><nav class="art-top" aria-label="Breadcrumb"><a href="/">Orr Biologicals</a> / <a href="/research/">Research methods</a></nav>\n'
        page += '<p class="art-cat">Educational research guide · Concepts, not validated hardware</p><h1>' + e(h1) + '</h1>\n'
        page += '<p class="art-meta">By <a href="/research/">Orr Biologicals</a> · Published <time datetime="2026-10-04">October 4, 2026</time></p>\n<div class="prose">' + body + '</div>\n'
        page += '<nav class="art-foot" aria-label="Next reading"><a href="/research/">Research methods</a><a href="/glossary">Glossary</a><a href="/blog/">All research notes</a><a href="/cyanoflow">Cyanoflow</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a></nav></main>\n<script src="/js/consent.js" defer></script>\n<script src="/js/navigation.js?v=20260930a" defer></script>\n</body>\n</html>\n'
        path = ROOT / rel; path.parent.mkdir(parents=True, exist_ok=True); path.write_text(page, encoding='utf-8')
    print('Built curated research hub, glossary and single-cell methods guide')


if __name__ == '__main__': build()
