export const CFG = {
  world: { w: 3600, h: 3600 },
  tick: 1000 / 30,
  player: { r: 9, speed: 92, hp: 100 },
  resources: [
    { kind: "light",  color: "#ffe9a3", weight: 0.34, energy: 6,  ep: 0.10 },
    { kind: "carbon", color: "#a5e8b8", weight: 0.26, energy: 2,  ep: 0.12 },
    { kind: "nitro",  color: "#8fd4ff", weight: 0.22, energy: 1,  ep: 0.14 },
    { kind: "phos",   color: "#e8b8ff", weight: 0.18, energy: 1,  ep: 0.18 },
  ],
  counts: { nutrients: 260, motes: 130, bubbles: 26 },
  bacteria: {
    grazer:      { color: "#e07a7a", speed: 55, sense: 150, dps: 9 },
    competitor:  { color: "#c9c9e0", speed: 42, sense: 110 },
    decomposer:  { color: "#9a8f6a", speed: 30, sense: 90 },
    beneficial:  { color: "#7ad0e0", speed: 48, sense: 160 },
  },
  divisionCost: { energy: 34 },
  stages: [
    { name: "Cell",        pop: 1 },
    { name: "Colony",      pop: 6 },
    { name: "Ecosystem",   pop: 16 },
    { name: "Reactor ops", pop: 34 },
    { name: "Industrial",  pop: 60 },
    { name: "Civilization",pop: 96 },
  ],
  buildings: {
    cluster:   { name: "Algae cluster",   cost: { energy: 30 },  desc: "+nutrient regrow nearby" },
    biofilm:   { name: "Biofilm patch",   cost: { energy: 45 },  desc: "slows grazers inside" },
    lightfarm: { name: "Light farm",      cost: { energy: 55 },  desc: "+light particles nearby" },
    hub:       { name: "Nutrient hub",    cost: { energy: 70 },  desc: "stores surplus, feeds cells" },
    nursery:   { name: "Nursery zone",    cost: { energy: 85 },  desc: "cheaper division nearby" },
  },
  upgrades: {
    led:     { name: "High-efficiency LEDs", desc: "+25% light energy",            costs: [40, 90, 170],  fx: [1.25, 1.5, 1.85] },
    co2:     { name: "CO₂ injection",        desc: "+carbon particles & growth",   costs: [50, 110, 200], fx: [1.2, 1.45, 1.75] },
    mix:     { name: "Circulation pump",     desc: "+speed, even nutrients",       costs: [35, 80, 150],  fx: [1.15, 1.35, 1.6] },
    sensor:  { name: "Sensor suite",         desc: "reveals threats + EP gain",    costs: [30, 70, 140],  fx: [1.15, 1.3, 1.5] },
    harvest: { name: "Auto-harvester",       desc: "passive biomass income",       costs: [60, 130, 240], fx: [0.02, 0.05, 0.09] },
  },
  evo: [
    { id: "photo1", branch: "Photosynthesis", name: "Improved light capture", cost: 6,  fx: { lightGain: 1.3 } },
    { id: "photo2", branch: "Photosynthesis", name: "Efficient photosystems", cost: 12, req: "photo1", fx: { lightGain: 1.35, drain: 0.9 } },
    { id: "photo3", branch: "Photosynthesis", name: "Low-light adaptation",   cost: 20, req: "photo2", fx: { lightGain: 1.25 } },
    { id: "def1",   branch: "Defense",        name: "Tougher cell wall",      cost: 6,  fx: { dmgTaken: 0.7 } },
    { id: "def2",   branch: "Defense",        name: "Chemical defense",       cost: 14, req: "def1", fx: { grazerFlee: 1 } },
    { id: "def3",   branch: "Defense",        name: "Escape flagella",        cost: 22, req: "def1", fx: { speed: 1.3 } },
    { id: "grow1",  branch: "Growth",         name: "Faster reproduction",    cost: 8,  fx: { divideCost: 0.8 } },
    { id: "grow2",  branch: "Growth",         name: "Efficient nutrient use", cost: 15, req: "grow1", fx: { nutrientGain: 1.35 } },
    { id: "grow3",  branch: "Growth",         name: "Carbon utilization",     cost: 24, req: "grow2", fx: { carbonGain: 1.4 } },
    { id: "env1",   branch: "Environment",    name: "Temperature tolerance",  cost: 10, fx: { tempResist: 1 } },
    { id: "env2",   branch: "Environment",    name: "pH tolerance",           cost: 18, req: "env1", fx: { phStable: 1 } },
    { id: "col1",   branch: "Colony",         name: "Biofilm formation",      cost: 12, fx: { buildingDiscount: 0.85 } },
    { id: "col2",   branch: "Colony",         name: "Resource sharing",       cost: 20, req: "col1", fx: { sharedEnergy: 1 } },
    { id: "col3",   branch: "Colony",         name: "Specialized cells",      cost: 30, req: "col2", fx: { epGain: 1.25 } },
  ],
};
