export const CFG = {
  world: { w: 3200, h: 3200 },
  tick: 1 / 30,
  player: {
    accel: 900, damp: 0.92, maxSpeed: 190, r: 10, hp: 100,
    regenDelay: 4, regenRate: 2.2,
  },
  eat: { magnet: 64, pull: 340, radius: 15 },
  energy: { basal: 0.55, lightBase: 3.2 },
  divide: { cost: 26, intervalMin: 0.9 },
  ep: { perMote: 0.12, perDivide: 0.6, perPredation: 0.5 },
  resources: [
    { kind: "light",  color: "#ffe9a3", weight: .34, energy: 5, ep: .10 },
    { kind: "carbon", color: "#a5e8b8", weight: .26, energy: 2, ep: .12 },
    { kind: "nitro",  color: "#8fd4ff", weight: .22, energy: 2, ep: .14 },
    { kind: "phos",   color: "#e8b8ff", weight: .18, energy: 2, ep: .20 },
  ],
  counts: { nutrients: 240 },
  bacteria: {
    grazer:     { color: "#e07a7a", speed: 74, sense: 190, dps: 9,  biteCd: .8 },
    competitor: { color: "#c9c9e0", speed: 52, sense: 140 },
    decomposer: { color: "#9a8f6a", speed: 34, sense: 90 },
    beneficial: { color: "#7ad0e0", speed: 60, sense: 200 },
    pathogen:   { color: "#d06ac9", speed: 66, sense: 230, dps: 14, biteCd: 1.1 },
  },
  predation: { popNeeded: 22, epReward: .5 },
  buildings: {
    cluster:   { name: "Algae cluster", cost: 24, desc: "Nutrients regrow nearby" },
    biofilm:   { name: "Biofilm patch", cost: 36, desc: "Grazers slow & flee inside" },
    lightfarm: { name: "Light farm",    cost: 44, desc: "Steady light energy aura" },
    hub:       { name: "Nutrient hub",  cost: 55, desc: "Feeds nearby cells slowly" },
    nursery:   { name: "Nursery zone",  cost: 65, desc: "Divisions cost 30% less here" },
  },
  upgrades: {
    led:     { name: "High-efficiency LEDs", desc: "+25% light energy per level",  costs: [30, 70, 130], fx: [1.25, 1.5, 1.85] },
    co2:     { name: "CO₂ injection",        desc: "Carbon motes worth more",      costs: [40, 90, 160], fx: [1.25, 1.5, 1.8] },
    mix:     { name: "Circulation pump",     desc: "Swim faster, world feels lighter", costs: [25, 60, 110], fx: [1.12, 1.28, 1.5] },
    sensor:  { name: "Sensor suite",         desc: "+EP gain, threat pings",       costs: [20, 50, 95],  fx: [1.15, 1.35, 1.6] },
    harvest: { name: "Auto-harvester",       desc: "Passive biomass/sec",          costs: [45, 100, 180], fx: [.03, .07, .13] },
  },
  evo: [
    { id: "photo1", branch: "Photosynthesis", name: "Improved light capture", cost: 5,  fx: { lightGain: 1.35 } },
    { id: "photo2", branch: "Photosynthesis", name: "Efficient photosystems", cost: 11, req: "photo1", fx: { lightGain: 1.3, drain: .88 } },
    { id: "photo3", branch: "Photosynthesis", name: "Low-light adaptation",   cost: 19, req: "photo2", fx: { lightGain: 1.3, magnet: 1.3 } },
    { id: "def1",   branch: "Defense",        name: "Tougher cell wall",      cost: 5,  fx: { dmgTaken: .65 } },
    { id: "def2",   branch: "Defense",        name: "Chemical defense",       cost: 12, req: "def1", fx: { grazerFlee: 1 } },
    { id: "def3",   branch: "Defense",        name: "Escape flagella",        cost: 20, req: "def1", fx: { speed: 1.35 } },
    { id: "grow1",  branch: "Growth",         name: "Faster reproduction",    cost: 7,  fx: { divideCost: .78 } },
    { id: "grow2",  branch: "Growth",         name: "Efficient nutrient use", cost: 14, req: "grow1", fx: { nutrientGain: 1.4 } },
    { id: "grow3",  branch: "Growth",         name: "Carbon utilization",     cost: 22, req: "grow2", fx: { carbonGain: 1.45 } },
    { id: "env1",   branch: "Environment",    name: "Temperature tolerance",  cost: 9,  fx: { tempResist: 1 } },
    { id: "env2",   branch: "Environment",    name: "pH tolerance",           cost: 16, req: "env1", fx: { phStable: 1 } },
    { id: "col1",   branch: "Colony",         name: "Biofilm formation",      cost: 11, fx: { buildDiscount: .85 } },
    { id: "col2",   branch: "Colony",         name: "Resource sharing",       cost: 18, req: "col1", fx: { sharedEnergy: 1 } },
    { id: "col3",   branch: "Colony",         name: "Specialized cells",      cost: 27, req: "col2", fx: { epGain: 1.3 } },
  ],
  stages: [
    { name: "Cell", pop: 1 }, { name: "Colony", pop: 6 }, { name: "Ecosystem", pop: 16 },
    { name: "Reactor ops", pop: 30 }, { name: "Industrial", pop: 52 }, { name: "Civilization", pop: 84 },
  ],
};

export const ACH = [
  { id: "evolved",   name: "First Evolution",       desc: "Spend EP on a trait" },
  { id: "builder",   name: "Architect",             desc: "Place your first structure" },
  { id: "colony",    name: "Colony Founder",        desc: "Grow to 6 cells" },
  { id: "ecosystem", name: "Ecosystem Manager",     desc: "Grow to 16 cells" },
  { id: "predator",  name: "Apex of the Column",    desc: "Absorb your first bacterium" },
  { id: "operator",  name: "Reactor Operator",      desc: "Take over reactor operations" },
  { id: "survivor",  name: "The Culture Remembers", desc: "Regrow after losing your cell" },
];
